NewsPortal/Models/Noticia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewsPortal.Models
{
    public class Noticia
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public DateTime Data { get; set; }
        public string Conteudo { get; set; }

    }
}

NewsPortal/Models/RepositorioNoticias.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewsPortal.Models
{
    public class RepositorioNoticias
    {
        private static List<Noticia> noticias;

        public static List<Noticia> Noticias
        {
            get
            {
                if (noticias == null)
                    CriarNoticias();
                return noticias;
            }
        }

        private static void CriarNoticias()
        {
            noticias = new List<Noticia>();

            noticias.Add(new Noticia
            {
                Id = 1,
                Titulo = "Trabalhando com Asp.Net",
                Autor = "Gabriel",
                Data = DateTime.Today,
                Conteudo = "Essa é a primeira fase de trabalho com Asp.NET, meio que perdido estou mas está sendo bom programar com esse framework."

            });
            
            noticias.Add(new Noticia
            {
                Id = 2,
                Titulo = "Nova",
                Autor = "Gabriel",
                Data = DateTime.Today,
                Conteudo = "Essa é uma nova notícia feita.Tem que ter mais de 100 caracteres é isso. Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem"

            });
            noticias.Add(new Noticia
            {
                Id = 3,
                Titulo = "Trabalhando com Asp.Net",
                Autor = "Gabriel",
                Data = DateTime.Today,
                Conteudo = "Essa é a primeira fase de trabalho com Asp.NET, meio que perdido estou mas está sendo bom programar com esse framework."

            });
            noticias.Add(new Noticia
            {
                Id = 4,
                Titulo = "Trabalhando com Asp.Net",
                Autor = "Gabriel",
                Data = DateTime.Today,
                Conteudo = "Essa é a primeira fase de trabalho com Asp.NET, meio que perdido estou mas está sendo bom programar com esse framework."

            });
            noticias.Add(new Noticia
            {
                Id = 5,
                Titulo = "Trabalhando com Asp.Net",
                Autor = "Gabriel",
                Data = DateTime.Today,
                Conteudo = "Essa é a primeira fase de trabalho com Asp.NET, meio que perdido estou mas está sendo bom programar com esse framework."

            });
            noticias.Add(new Noticia
            {
                Id = 1,
                Titulo = "Trabalhando com Asp.Net",
                Autor = "Gabriel",
                Data = DateTime.Today,
                Conteudo = "Essa é a primeira fase de trabalho com Asp.NET, meio que perdido estou mas está sendo bom programar com esse framework."

            });
        }
    }
}

NewsPortal/Controllers/NoticiasController.cs
using NewsPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsPortal.Controllers
{
    public class NoticiasController : Controller
    {
        // GET: Noticias
        public ActionResult Index()
        {
            return View(RepositorioNoticias.Noticias);
        }

        public ActionResult Detalhes(int id)
        {
            var noticias = RepositorioNoticias.Noticias.FirstOrDefault(n => n.Id == id);
            return View(noticias);
        }

        public ActionResult Buscar(string texto)
        {
            var noticias = RepositorioNoticias.Noticias.Where(n => n.Titulo.Contains(texto) || n.Conteudo.Contains(texto));
            return View(noticias);
        }
    }
}

NewsPortal/Views/Noticias/Buscar.cshtml
@model IEnumerable<NewsPortal.Models.Noticia>

@{
    ViewBag.Title = "Buscar notícias";
}

@foreach (var item in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <p>@item.Titulo)</p>
        </div>
        <div class="panel-body">
            <p>@item.Conteudo.Substring(0, 100) ...</p>
            @Html.DisplayFor(modelItem => item.Autor)
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Ler mais", "Detalhes", new { id = @item.Id }, new { @class = "btn btn-default" })
        </div>
    </div>
}

NewsPortal/Views/Noticias/Detalhes.cshtml
@model NewsPortal.Models.Noticia

@{
    ViewBag.Title = "Detalhes da notícia";
}

<h2>@Model.Titulo</h2>

<p>Publicado por <strong>@Model.Autor</strong> em <strong>@Model.Data.ToString("dd/MM/yyyy")</strong></p>

<p>@Model.Conteudo</p>

NewsPortal/Views/Noticias/Index.cshtml
@model IEnumerable<NewsPortal.Models.Noticia>

@{
    ViewBag.Title = "Página Inicial";
}

@foreach (var item in Model) {
    <div class="panel panel-default">
        <div class="panel-heading">
            <p>@item.Titulo</p>
        </div>
        <div class="panel-body">
            <p>@item.Conteudo.Substring(0, 100) ...</p>
            <p><strong>Autor: </strong>@Html.DisplayFor(modelItem => item.Autor)</p>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Ler mais", "Detalhes", new { id = @item.Id }, new { @class = "btn btn-default" })
        </div>
    </div>
}

NewsPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu portal de Notícias</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h1>Portal de Notícias</h1>
        </div>
        <div class="navbar-header">
            @Html.ActionLink("Início", "Index", "Noticias", null, new { @class = "navbar-brand" })
        </div>
       
        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <p class="panel-title">Buscar Notícias</p>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("Buscar", "Noticias", FormMethod.Get))
                        {
                            <input type="text" class="form-control" name="texto" placeholder="Buscar por..." />
                        }

                    </div>

                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="container body-content">
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>